import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import { FaBars, FaUser, FaShoppingCart } from 'react-icons/fa'

export default function Night() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-container-fluid">
        <header className="row">
          <nav className="navbar navbar-expand-lg  ">
            <div className="container-fluid">
              <a className="navbar-brand" href="#">
                <Image
                  src="/docs/5.1/assets/brand/bootstrap-logo.svg"
                  alt=""
                  width={30}
                  height={24}
                />
              </a>
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                {/* <i className="navbar-toggler-icon fa-solid fa-bars" /> */}
                <FaBars className="navbar-toggler-icon fa-solid fa-bars" />
                {/* <span class="navbar-toggler-icon"></span> */}
              </button>
              <div
                className="collapse navbar-collapse"
                id="navbarSupportedContent"
              >
                <div className="me-auto" />
                <ul className="navbar-nav mb-2 mb-lg-0">
                  <li className="nav-item">
                    <a className="nav-link active" aria-current="page" href="#">
                      夜市導覽
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      美味商城
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      趣味遊戲
                    </a>
                  </li>
                  <div className="nav-icon-items">
                    <li className="nav-item">
                      <a className="nav-link" href="#">
                        <div className="nav-icons">
                          {/* <i className="fa-solid fa-bars" /> */}
                          <FaBars className="fa-solid fa-bars" />
                          {/* <i className="fa-solid fa-user" /> */}
                          <FaUser className="fa-solid fa-user" />
                        </div>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link" href="#">
                        <div className="nav-icons">
                          {/* <i className="fa-solid fa-cart-shopping" /> */}
                          <FaShoppingCart className="fa-solid fa-cart-shopping" />
                        </div>
                      </a>
                    </li>
                  </div>
                </ul>
                {/* <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form> */}
              </div>
            </div>
          </nav>
        </header>
        <main className="row">
          <div className="simple-news">
            <div className="col-1">
              <h6>即時消息</h6>
            </div>
            <div className="col-11 news">
              <p>即時消息即時消息即時消息即時消息即時消息即時消息</p>
              <p>即時消息即時消息即時消息即時消息即時消息即時消息</p>
              <p>即時消息即時消息即時消息即時消息即時消息即時消息</p>
              <p>即時消息即時消息即時消息即時消息即時消息即時消息</p>
              <p>即時消息即時消息即時消息即時消息即時消息即時消息</p>
            </div>
          </div>
          <div className="kv" />
          <div className="section">
            <h1>aaaaa</h1>
          </div>
          <div className="section" />
        </main>
        <footer>
          <div className="footer">fffffff</div>
          <h1>GFGFFH</h1>
        </footer>
      </div>
    </>
  )
}
